// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyManagementService.Repository;

#nullable disable

namespace PropertyManagementService.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20250618104307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("propertydb")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyAmenities", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities", "propertydb");
                });

            modelBuilder.Entity("PropertyManagementService.Models.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RepairCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prop_MaintenanceRecords", "propertydb");
                });

            modelBuilder.Entity("PropertyManagementService.Models.PropertyAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Prop_PropertyAmenities", "propertydb");
                });

            modelBuilder.Entity("PropertyManagementService.Models.PropertyFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Prop_PropertyFeatures", "propertydb");
                });

            modelBuilder.Entity("PropertyManagementService.Models.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Prop_PropertyImages", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Amenities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Amenities_Name");

                    b.ToTable("Amenities", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DownPaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Booking", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.CondominiumUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("SizeSquareFeet")
                        .HasColumnType("integer");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_CondominiumUnits");

                    b.HasIndex("PropertyId");

                    b.ToTable("CondominiumUnits", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.ContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ContactDetail", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_LeaseAgreements_TenantId");

                    b.ToTable("LeaseAgreement", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("FairValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("InsurableValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsRentable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSaleable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumberOfStories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertyManagerId")
                        .HasColumnType("text");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal?>("RentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("YearOfCommissionOrPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("EXTRACT(YEAR FROM CURRENT_TIMESTAMP)");

                    b.HasKey("Id")
                        .HasName("PK_Properties");

                    b.HasIndex("ApprovalStatus")
                        .HasDatabaseName("IX_Properties_ApprovalStatus");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Properties_OwnerId");

                    b.ToTable("Prop_Properties", "propertydb");

                    b.HasDiscriminator<string>("PropertyType").HasValue("Property");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyCertifications", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectiveActions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InspectionNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastInspectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextInspectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegulationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Violations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyCompliance", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyFeatures", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGarden")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGym")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHeating")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasInternet")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasParking")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPool")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSecurity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("boolean");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyFeatures", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyRegulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplianceRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentationRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Penalties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyRegulations", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyServices", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComplianceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("PropertyStandards", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationPreferences")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTelephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tenant", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.InspectionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TerminationProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TerminationProcessId");

                    b.ToTable("InspectionReport", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.RenewalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaseAgreementId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NewMonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<string>("NewTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RenewalRequest", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaseAgreementId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SecurityDepositDeduction")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseAgreementId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("TerminationProcess", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.TownhouseCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CommonAreaSize")
                        .HasColumnType("numeric");

                    b.Property<int>("NumberOfUnits")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_TownhouseClusters");

                    b.HasIndex("PropertyId");

                    b.ToTable("TownhouseClusters", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.WingDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommonArea")
                        .HasColumnType("integer");

                    b.Property<int>("FloorArea")
                        .HasColumnType("integer");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_WingDetails");

                    b.HasIndex("PropertyId");

                    b.ToTable("WingDetails", "propertydb");
                });

            modelBuilder.Entity("SharedKernel.Models.BungalowProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Bungalow");
                });

            modelBuilder.Entity("SharedKernel.Models.CommercialProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<int>("NumberOfWings")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalParkingAreaPerFloor")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("Commercial");
                });

            modelBuilder.Entity("SharedKernel.Models.CondominiumProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<decimal>("HOAFees")
                        .HasColumnType("numeric");

                    b.Property<int>("NumberOfUnitsPerFloor")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Condominium");
                });

            modelBuilder.Entity("SharedKernel.Models.TownhouseProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<int>("NumberOfClusters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasDiscriminator().HasValue("Townhouse");
                });

            modelBuilder.Entity("SharedKernel.Models.VacantLandProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<decimal>("Acreage")
                        .HasMaxLength(50)
                        .HasColumnType("numeric");

                    b.Property<string>("BlockNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("VacantLand");
                });

            modelBuilder.Entity("SharedKernel.Models.VillaProperty", b =>
                {
                    b.HasBaseType("SharedKernel.Models.Property");

                    b.Property<int>("NumberOfBathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfBedrooms")
                        .HasColumnType("integer");

                    b.ToTable("Prop_Properties", "propertydb", t =>
                        {
                            t.Property("NumberOfBathrooms")
                                .HasColumnName("VillaProperty_NumberOfBathrooms");

                            t.Property("NumberOfBedrooms")
                                .HasColumnName("VillaProperty_NumberOfBedrooms");
                        });

                    b.HasDiscriminator().HasValue("Villa");
                });

            modelBuilder.Entity("PropertyAmenities", b =>
                {
                    b.HasOne("SharedKernel.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Models.Booking", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.CondominiumUnit", b =>
                {
                    b.HasOne("SharedKernel.Models.CondominiumProperty", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.ContactDetail", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", null)
                        .WithMany("LeaseAgreements")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("LeaseAgreements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyCertification", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Certifications")
                        .HasForeignKey("SharedKernel.Models.PropertyCertification", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyCompliance", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Compliance")
                        .HasForeignKey("SharedKernel.Models.PropertyCompliance", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyFeatures", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Features")
                        .HasForeignKey("SharedKernel.Models.PropertyFeatures", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyRegulation", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Regulations")
                        .HasForeignKey("SharedKernel.Models.PropertyRegulation", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyService", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Services")
                        .HasForeignKey("SharedKernel.Models.PropertyService", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.PropertyStandard", b =>
                {
                    b.HasOne("SharedKernel.Models.Property", "Property")
                        .WithOne("Standards")
                        .HasForeignKey("SharedKernel.Models.PropertyStandard", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.InspectionReport", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenants.TerminationProcess", "TerminationProcess")
                        .WithMany("InspectionReports")
                        .HasForeignKey("TerminationProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminationProcess");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.RenewalRequest", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("RenewalRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.HasOne("SharedKernel.Models.LeaseAgreement", "LeaseAgreement")
                        .WithOne("TerminationProcess")
                        .HasForeignKey("SharedKernel.Models.Tenants.TerminationProcess", "LeaseAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("TerminationProcesses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaseAgreement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.TownhouseCluster", b =>
                {
                    b.HasOne("SharedKernel.Models.TownhouseProperty", "Property")
                        .WithMany("Clusters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.WingDetails", b =>
                {
                    b.HasOne("SharedKernel.Models.CommercialProperty", "Property")
                        .WithMany("Wings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.Navigation("TerminationProcess")
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Models.Property", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Compliance");

                    b.Navigation("Features");

                    b.Navigation("LeaseAgreements");

                    b.Navigation("Regulations");

                    b.Navigation("Services");

                    b.Navigation("Standards");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Contacts");

                    b.Navigation("LeaseAgreements");

                    b.Navigation("RenewalRequests");

                    b.Navigation("TerminationProcesses");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.Navigation("InspectionReports");
                });

            modelBuilder.Entity("SharedKernel.Models.CommercialProperty", b =>
                {
                    b.Navigation("Wings");
                });

            modelBuilder.Entity("SharedKernel.Models.CondominiumProperty", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("SharedKernel.Models.TownhouseProperty", b =>
                {
                    b.Navigation("Clusters");
                });
#pragma warning restore 612, 618
        }
    }
}
