// <auto-generated />
using System;
using AuthenticationService.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthenticationService.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authdb")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedKernel.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Auth_Permissions", "authdb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Category = "User Management",
                            Description = "View users",
                            Name = "users.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Category = "User Management",
                            Description = "Create users",
                            Name = "users.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Category = "User Management",
                            Description = "Edit users",
                            Name = "users.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Category = "User Management",
                            Description = "Delete users",
                            Name = "users.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Category = "Role Management",
                            Description = "View roles",
                            Name = "roles.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Category = "Role Management",
                            Description = "Create roles",
                            Name = "roles.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Category = "Role Management",
                            Description = "Edit roles",
                            Name = "roles.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Category = "Role Management",
                            Description = "Delete roles",
                            Name = "roles.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Category = "Role Management",
                            Description = "Assign roles to users",
                            Name = "roles.assign"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Category = "Property Management",
                            Description = "View properties",
                            Name = "properties.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Category = "Property Management",
                            Description = "Create properties",
                            Name = "properties.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Category = "Property Management",
                            Description = "Edit properties",
                            Name = "properties.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Category = "Property Management",
                            Description = "Delete properties",
                            Name = "properties.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Category = "Property Management",
                            Description = "Approve properties",
                            Name = "properties.approve"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Category = "Property Management",
                            Description = "Manage property maintenance",
                            Name = "properties.maintenance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Category = "Property Management",
                            Description = "Manage property budget",
                            Name = "properties.budget"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Category = "Tenant Management",
                            Description = "View tenants",
                            Name = "tenants.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Category = "Tenant Management",
                            Description = "Create tenants",
                            Name = "tenants.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Category = "Tenant Management",
                            Description = "Edit tenants",
                            Name = "tenants.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Category = "Tenant Management",
                            Description = "Delete tenants",
                            Name = "tenants.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000005"),
                            Category = "Tenant Management",
                            Description = "Manage tenant leases",
                            Name = "tenants.leases"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000006"),
                            Category = "Tenant Management",
                            Description = "Process tenant payments",
                            Name = "tenants.payments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000007"),
                            Category = "Tenant Management",
                            Description = "View financial reports",
                            Name = "tenants.reports"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            Category = "Sales Management",
                            Description = "View sales",
                            Name = "sales.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            Category = "Sales Management",
                            Description = "Create sales",
                            Name = "sales.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            Category = "Sales Management",
                            Description = "Edit sales",
                            Name = "sales.edit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            Category = "Sales Management",
                            Description = "Approve sales",
                            Name = "sales.approve"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            Category = "Sales Management",
                            Description = "Process down payments",
                            Name = "sales.downpayments"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000006"),
                            Category = "Sales Management",
                            Description = "Schedule property tours",
                            Name = "sales.tours"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            Category = "Tenant Portal",
                            Description = "View properties in portal",
                            Name = "portal.properties.view"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            Category = "Tenant Portal",
                            Description = "Schedule property tours",
                            Name = "portal.tours.schedule"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000003"),
                            Category = "Tenant Portal",
                            Description = "Reserve properties",
                            Name = "portal.properties.reserve"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000004"),
                            Category = "Tenant Portal",
                            Description = "Make down payments",
                            Name = "portal.payments.down"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000005"),
                            Category = "Tenant Portal",
                            Description = "View rent schedule",
                            Name = "portal.rent.schedule"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000006"),
                            Category = "Tenant Portal",
                            Description = "Make payments",
                            Name = "portal.payments.make"
                        });
                });

            modelBuilder.Entity("SharedKernel.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Auth_Roles", "authdb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator with full access",
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regular user with basic access",
                            IsSystemRole = true,
                            Name = "User"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages property registrations, tenant onboarding, and lease administration",
                            IsSystemRole = true,
                            Name = "Estates Officer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oversees property approvals, maintenance, and budget management",
                            IsSystemRole = true,
                            Name = "Property Manager"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Addresses tenant maintenance requests and manages work orders",
                            IsSystemRole = true,
                            Name = "Maintenance Officer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Processes rent payments, issues invoices, and handles financial reporting",
                            IsSystemRole = true,
                            Name = "Finance Team"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Handles property tours, bookings, and client onboarding",
                            IsSystemRole = true,
                            Name = "Sales Officer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages sales team and property down-payment processing",
                            IsSystemRole = true,
                            Name = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Accesses tenant portal for property viewing, payments, and maintenance requests",
                            IsSystemRole = true,
                            Name = "Tenant"
                        });
                });

            modelBuilder.Entity("SharedKernel.Models.RoleAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("AffectedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Auth_RoleAuditLogs", "authdb");
                });

            modelBuilder.Entity("SharedKernel.Models.RoleHierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildRoleId");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("Auth_RoleHierarchies", "authdb");
                });

            modelBuilder.Entity("SharedKernel.Models.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Auth_RolePermissions", "authdb");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0001-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0001-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("00000000-0000-0000-0004-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0003-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("00000000-0000-0000-0005-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("00000000-0000-0000-0006-000000000006")
                        });
                });

            modelBuilder.Entity("SharedKernel.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auth_Users", "authdb");
                });

            modelBuilder.Entity("SharedKernel.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Auth_UserRoles", "authdb");
                });

            modelBuilder.Entity("SharedKernel.Models.RoleAuditLog", b =>
                {
                    b.HasOne("SharedKernel.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SharedKernel.Models.RoleHierarchy", b =>
                {
                    b.HasOne("SharedKernel.Models.Role", "ChildRole")
                        .WithMany("ParentRoles")
                        .HasForeignKey("ChildRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Role", "ParentRole")
                        .WithMany("ChildRoles")
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildRole");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("SharedKernel.Models.RolePermission", b =>
                {
                    b.HasOne("SharedKernel.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SharedKernel.Models.UserRole", b =>
                {
                    b.HasOne("SharedKernel.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedKernel.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SharedKernel.Models.Role", b =>
                {
                    b.Navigation("ChildRoles");

                    b.Navigation("ParentRoles");

                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
