// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantManagementService.Repository;

#nullable disable

namespace TenantManagementService.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenantdb")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedKernel.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DownPaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenant_Bookings", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.ContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ContactDetail", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Tenant_Invoices", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenant_LeaseAgreements", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingEntity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationPreferences")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTelephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tenant_Tenants", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.InspectionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TerminationProcessId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TerminationProcessId");

                    b.ToTable("InspectionReports", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.RenewalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaseAgreementId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NewMonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<string>("NewTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Tenant_RenewalRequests", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InitiatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeaseAgreementId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SecurityDepositDeduction")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseAgreementId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Tenant_TerminationProcesses", "tenantdb");
                });

            modelBuilder.Entity("SharedKernel.Models.Booking", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("Bookings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.ContactDetail", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Models.Invoice", b =>
                {
                    b.HasOne("SharedKernel.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("LeaseAgreements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.Payment", b =>
                {
                    b.HasOne("SharedKernel.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.InspectionReport", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenants.TerminationProcess", "TerminationProcess")
                        .WithMany("InspectionReports")
                        .HasForeignKey("TerminationProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminationProcess");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.RenewalRequest", b =>
                {
                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("RenewalRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.HasOne("SharedKernel.Models.LeaseAgreement", "LeaseAgreement")
                        .WithOne("TerminationProcess")
                        .HasForeignKey("SharedKernel.Models.Tenants.TerminationProcess", "LeaseAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedKernel.Models.Tenant", "Tenant")
                        .WithMany("TerminationProcesses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaseAgreement");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SharedKernel.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SharedKernel.Models.LeaseAgreement", b =>
                {
                    b.Navigation("TerminationProcess")
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Models.Tenant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Contacts");

                    b.Navigation("LeaseAgreements");

                    b.Navigation("RenewalRequests");

                    b.Navigation("TerminationProcesses");
                });

            modelBuilder.Entity("SharedKernel.Models.Tenants.TerminationProcess", b =>
                {
                    b.Navigation("InspectionReports");
                });
#pragma warning restore 612, 618
        }
    }
}
