# Generated by Django 5.2.12 on 2026-03-27 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("receipt", "Receipt"),
                            ("invoice", "Invoice"),
                            ("bank_statement", "Bank Statement"),
                            ("payroll", "Payroll"),
                        ],
                        default="generic",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("needs_review", "Needs Review"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("upload", models.FileField(upload_to="uploads/")),
                ("export_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("extracted_text", models.TextField(blank=True)),
                ("tables_json", models.JSONField(default=list)),
                ("extracted_fields", models.JSONField(default=dict)),
                ("avg_confidence", models.FloatField(blank=True, null=True)),
                ("azure_latency_s", models.FloatField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="page_images/"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.job",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("word", models.CharField(max_length=500)),
                ("confidence", models.FloatField()),
                ("polygon_json", models.JSONField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("corrected_value", models.CharField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "page_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="documents.pageresult",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["confidence"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["owner", "status"], name="documents_j_owner_i_819a57_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pageresult",
            unique_together={("job", "page_number")},
        ),
    ]
