# Generated by Django 5.2.12 on 2026-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_fix_upload_to"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="documents_a_user_id_481fbb_idx",
            old_name="auditlog_user_ts_idx",
        ),
    ]
