# Generated by Django 5.2.12 on 2026-04-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_reviewflag_admin_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewflag',
            name='column_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='row_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='span_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='span_offset',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewflag',
            name='table_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
