# Generated by Django 5.2.12 on 2026-04-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_supervisor_alter_user_role_and_more'),
        ('documents', '0010_job_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='batchupload',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.department'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['department', 'timestamp'], name='documents_a_departm_656481_idx'),
        ),
        migrations.AddIndex(
            model_name='batchupload',
            index=models.Index(fields=['department', 'created_at'], name='documents_b_departm_1db2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['department', 'status'], name='documents_j_departm_8316f7_idx'),
        ),
    ]
